/**
 * Codegen: embed the managed Pi extension sources into a TypeScript module so
 * phantombot's compiled binary can stamp them onto disk at runtime.
 *
 * Why a generated constants module (vs. `import ... with { type: "text" }`)?
 * The text-import form is NOT tsc-safe in this toolchain — `tsc --noEmit`
 * rejects it. Generating a plain `.ts` with the file contents as JSON-encoded
 * string literals sidesteps that entirely and keeps `bun build --compile`
 * self-contained (no runtime fs read of the repo, which won't exist in the
 * shipped binary).
 *
 * Run: `bun run gen:pi-extension` (regenerate whenever the extension changes;
 * tests/lib-piExtensionAssets.test.ts fails CI if the checked-in module drifts).
 */

import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(HERE, "..");
const EXTENSIONS = [
  {
    constant: "PI_EXTENSION_FILES",
    directory: "capability-routing",
    files: ["index.ts", "tools.ts", "spawnPi.ts", "README.md"],
    hashConstant: "PI_EXTENSION_ASSETS_HASH",
  },
  {
    constant: "PI_DYNAMIC_CONTEXT_EXTENSION_FILES",
    directory: "dynamic-context",
    files: ["index.ts", "tools.ts"],
    hashConstant: "PI_DYNAMIC_CONTEXT_EXTENSION_ASSETS_HASH",
  },
] as const;
const OUT_FILE = join(REPO_ROOT, "src", "lib", "piExtensionAssets.generated.ts");

function hashEntries(entries: Array<[string, string]>): string {
  const h = createHash("sha256");
  for (const [rel, content] of [...entries].sort((a, b) => a[0].localeCompare(b[0]))) {
    h.update(rel, "utf8");
    h.update("\0", "utf8");
    h.update(content, "utf8");
    h.update("\0", "utf8");
  }
  return h.digest("hex");
}

const body = [
  "// GENERATED by scripts/genPiExtensionAssets.ts — DO NOT EDIT. Run: bun run gen:pi-extension",
  "//",
  "// Embeds managed pi-extension sources so phantombot's compiled binary can",
  "// stamp them into ~/.pi/agent/extensions/ at startup.",
  "",
  ...EXTENSIONS.flatMap((spec) => {
    const entries: Array<[string, string]> = spec.files.map((rel) => [
      rel,
      readFileSync(join(REPO_ROOT, "pi-extension", spec.directory, rel), "utf8"),
    ]);
    const hash = hashEntries(entries);
    return [
      `export const ${spec.constant}: Record<string, string> = {`,
      ...entries.map(
        ([rel, content]) => `  ${JSON.stringify(rel)}: ${JSON.stringify(content)},`,
      ),
      "};",
      "",
      `export const ${spec.hashConstant} = ${JSON.stringify(hash)};`,
      "",
    ];
  }),
].join("\n");

writeFileSync(OUT_FILE, body, "utf8");
// eslint-disable-next-line no-console
console.log(
  `wrote ${OUT_FILE} (${EXTENSIONS.map((spec) => `${spec.directory} (${spec.files.length})`).join(", ")})`,
);
